# Generated by Django 4.2.5 on 2023-10-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emal',
            new_name='email',
        ),
    ]
